""" Migration

Revision ID: 3dcb30f309ce
Revises: 83bf8cf06891
Create Date: 2022-05-10 17:38:51.590194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dcb30f309ce'
down_revision = '83bf8cf06891'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dislikes_pitch_id_fkey', 'dislikes', type_='foreignkey')
    op.drop_column('dislikes', 'pitch_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dislikes', sa.Column('pitch_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('dislikes_pitch_id_fkey', 'dislikes', 'pitches', ['pitch_id'], ['id'])
    # ### end Alembic commands ###
