""" Migration

Revision ID: 561e7cda29c5
Revises: 0855c34a18a5
Create Date: 2022-05-10 17:36:48.051480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '561e7cda29c5'
down_revision = '0855c34a18a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'pitch_text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pitch_text', sa.VARCHAR(length=400), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
