""" Migration

Revision ID: 83bf8cf06891
Revises: 561e7cda29c5
Create Date: 2022-05-10 17:37:06.777040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83bf8cf06891'
down_revision = '561e7cda29c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pitch_text', sa.String(length=400), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'pitch_text')
    # ### end Alembic commands ###
