""" Migration

Revision ID: 8b0976164f3a
Revises: 3dcb30f309ce
Create Date: 2022-05-10 17:39:14.084498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b0976164f3a'
down_revision = '3dcb30f309ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dislikes', sa.Column('pitch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'dislikes', 'pitches', ['pitch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dislikes', type_='foreignkey')
    op.drop_column('dislikes', 'pitch_id')
    # ### end Alembic commands ###
